version: "3.3"

volumes:
  nevadev-data:

networks:
  nevadev:

services:
  nevadev:
    container_name: nevadev
    build: .
    ports:
      - "8080:80"
    volumes:
      - nevadev-data:/code
    networks:
      - nevadev
