name: Deploy Container to Remote Host

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:latest

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Docker-Compose Remote Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Shutdown existing Containers
        run: |
          docker-compose -H ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} down

      - name: Run compose on Host
        run: |
          docker-compose -H ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} up -d --build

      - name: Clean up
        run: rm -rf ~/.ssh
